### ISSUE TITLE
Trying to install hyperglance automations using terraform 

### ISSUE THREAD

**Issue by rmarcandier13** [hyperglance/aws-rule-automations#2]
terraform plan                                                                                  ✔  3s 
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: eu-west-1

╷
│ Warning: Argument is deprecated
│
│   with module.hyperglance_automations.aws_s3_bucket.hyperglance_automations_bucket,
│   on ../modules/hyperglance-automations/main.tf line 28, in resource "aws_s3_bucket" "hyperglance_automations_bucket":
│   28:   acl    = "private"
│
│ Use the aws_s3_bucket_acl resource instead
╵
╷
│ Error: Invalid value for variable
│
│   on main.tf line 14, in module "hyperglance_automations":
│   14:   hyperglance_identity_arn = ""
│
│ The arn of the role under which Hyperglance is running must be set.
│
│ This was checked by the validation rule at ../modules/hyperglance-automations/variables.tf:32,5-15.

    ~/aws-rule-automations/deployment/terraform/automations    master ?1  terraform --version                                                                                    ✔
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.0
    ~/aws-rule-automations/deployment/terraform/automations    master ?1  aws --version                                                                                          ✔
aws-cli/2.5.6 Python/3.9.11 Linux/4.4.0-19041-Microsoft exe/x86_64.ubuntu.20 prompt/off
    ~/aws-rule-automations/deployment/terraform/automations    master ?1 

**Comment by daveagill** [comment]
Thanks for reporting this.

Error is due to `hyperglance_identity_arn` not being set. Readme has been amended to clarify this in [6b6d32969d2e17ea6a895fe8f3641ffe3b6cd29b](https://github.com/hyperglance/aws-rule-automations/commit/6b6d32969d2e17ea6a895fe8f3641ffe3b6cd29b)
